---
roles:
  - name: robertdebock.auditd
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.cron
  - name: robertdebock.users
collections:
  - name: community.general
  - name: ansible.posix
