---
- name: test if omsagent_version is set correctly
  assert:
    that:
      - omsagent_version is defined
    quiet: yes

- name: test if omsagent_tmp is set correctly
  assert:
    that:
      - omsagent_tmp is defined
    quiet: yes

- name: test if omsagent_owner is set correctly
  assert:
    that:
      - omsagent_owner is defined
    quiet: yes

- name: test if omsagent_group is set correctly
  assert:
    that:
      - omsagent_group is defined
    quiet: yes

- name: test if omsagent_id is set correctly
  assert:
    that:
      - omsagent_id is defined
    quiet: yes

- name: test if omsagent_shared_key is set correctly
  assert:
    that:
      - omsagent_shared_key is defined
    quiet: yes

- name: test if omsagent_domain is set correctly
  assert:
    that:
      - omsagent_domain is defined
    quiet: yes
