---
# tasks file for omsagent

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ omsagent_requirements }}"
    state: present

- name: download installation script
  get_url:
    url: "{{ omsagent_url }}"
    dest: "{{ omsagent_tmp }}"
    mode: "755"

- name: ensure directory exist
  file:
    path: /etc/opt/microsoft/omsagent
    state: directory
    mode: "0755"

- name: set proxy configuration
  template:
    src: proxy.conf.j2
    dest: /etc/opt/microsoft/omsagent/proxy.conf
    owner: "{{ omsagent_owner }}"
    group: "{{ omsagent_group }}"
    mode: "640"
  when:
    - omsagent_proxy is defined

- name: run script (can take a couple of minutes)
  command: "{{ omsagent_tmp }}/onboard_agent.sh"
  args:
    creates: omsagent-{{ omsagent_version }}.universal.{{ omsagent_creates_pattern }}.sh
    chdir: "{{ omsagent_tmp }}"
  notify:
    - wait for the script to finish

- name: flush handlers
  meta: flush_handlers

- name: start and enable omid service
  service:
    name: omid
    state: "{{ omsagent_service_state }}"
    enabled: yes
  when:
    - omsagent_service_state | length
