---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check version
      command: /opt/omi/bin/{{ item }} --version
      loop:
        - omiagent
        - omiconfigeditor
        - omigen
        - omireg
        - omiserver

    - name: check help
      command: /opt/omi/bin/{{ item }} --help
      loop:
        - omicli
